### ISSUE TITLE
React Peer Dependency set to v17

### ISSUE THREAD

**Issue by tfmertz** [ChiragRupani/fullscreen-react#2]
Looks like the devDependencies updated to React v18, but not the peerDependencies. Does this package have breaking changes with v18 of React, or was it just missed? It won't install into projects running v18 of react.

**Comment by ChiragRupani** [comment]
Unpinned peer dependency - It should install with React 18. Please install latest version using `npm i @chiragrupani/fullscreen-react` (it should be 1.2.1) and let me know if there is still issue.
