### ISSUE TITLE
Unable to parse source map

### ISSUE THREAD

**Issue by samarth-ramesh** [ChiragRupani/fullscreen-react#4]
Hi!
when running using ``npm run``, I get a ton of messages complaining about:

```
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/path-to-project/node_modules/@chiragrupani/fullscreen-react/src/DocumentFullScreen.tsx' file: 
Error: ENOENT: no such file or directory, open '/path-to-project/node_modules/@chiragrupani/fullscreen-react/src/DocumentFullScreen.tsx'
```
(added a line break).

What do I need to do to fix the error?

**Comment by ChiragRupani** [comment]
Fixed - Please install latest version `npm i @chiragrupani/fullscreen-react`. Please feel free to comment if issue still there. Moreover, you can ignore those warnings as it would not affect functionality.
