### ISSUE TITLE
close button

### ISSUE THREAD

**Issue by AlexR0v** [ChiragRupani/fullscreen-react#5]
when you switch to full-screen mode, if you move the cursor closer to the upper border, a round close button appears. How to remove it? there is no such button on mac os, only on windows

**Comment by ChiragRupani** [comment]
The close button is coming from browser you are using, I am afraid it can be removed.

**Comment by AlexR0v** [comment]
>  it can be removed.

you wanted to say probably can't be deleted? =), anyway thanks for your answer, now I know for sure that it doesn't come from your package
